name: Production Deployment

# Trigger: Only on push/merge to main branch
on:
  push:
    branches:
      - main

# Permissions for GitHub API access
permissions:
  contents: write
  pull-requests: write

# Prevent concurrent deployments
concurrency:
  group: production-deployment
  cancel-in-progress: false

env:
  NODE_VERSION: '20'
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  # ============================================================================
  # Phase 1: Build Validation
  # ============================================================================
  validate:
    name: Build Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          set -euo pipefail
          npm ci --prefer-offline --no-audit
        shell: bash

      - name: Run linting
        run: |
          set -euo pipefail
          npm run lint
        shell: bash

      - name: Run type checking
        run: |
          set -euo pipefail
          npm run type-check
        shell: bash

      - name: Run format check
        run: |
          set -euo pipefail
          npm run format:check
        shell: bash

      - name: Build Next.js application
        run: |
          set -euo pipefail
          npm run build
        env:
          # Required for build-time environment variables
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          MAIN_SITE_URL: ${{ secrets.MAIN_SITE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        shell: bash

      - name: ✅ Validation complete
        run: echo "All validation checks passed successfully"

  # ============================================================================
  # Phase 2: Database Migration
  # ============================================================================
  migrate:
    name: Database Migration
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: |
          set -euo pipefail
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        shell: bash

      - name: Run database migrations
        id: migrations
        run: |
          set -euo pipefail
          echo "Starting database migration..."
          
          # Run migrations and capture output
          supabase db push --include-all 2>&1 | tee migration_output.txt
          
          # Check if migrations were successful
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "✅ Migrations applied successfully"
            echo "migration_status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Migration failed"
            echo "migration_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        shell: bash

      - name: Display migration results
        if: always()
        run: |
          echo "=== Migration Output ==="
          cat migration_output.txt || echo "No migration output available"
        shell: bash

      - name: Upload migration logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: migration-logs
          path: migration_output.txt
          retention-days: 30

      - name: ❌ Migration failed - STOPPING deployment
        if: steps.migrations.outputs.migration_status == 'failed'
        run: |
          echo "::error::Database migration failed. Deployment aborted."
          echo "Check the migration logs artifact for details."
          exit 1

  # ============================================================================
  # Phase 3: Edge Functions Deployment
  # ============================================================================
  deploy-functions:
    name: Deploy Supabase Edge Functions
    runs-on: ubuntu-latest
    needs: [validate, migrate]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: |
          set -euo pipefail
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        shell: bash

      - name: Deploy Edge Functions
        id: functions
        run: |
          set -euo pipefail
          echo "Starting Edge Functions deployment..."
          
          # Deploy all functions (Deploys all functions in supabase/functions/)
          supabase functions deploy --no-verify-jwt 2>&1 | tee functions_output.txt
          
          # Check if deployment was successful
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "✅ All Edge Functions deployed successfully"
            echo "functions_status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Edge Functions deployment failed"
            echo "functions_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        shell: bash

      - name: Display deployment results
        if: always()
        run: |
          echo "=== Edge Functions Deployment Output ==="
          cat functions_output.txt || echo "No deployment output available"
        shell: bash

      - name: Upload deployment logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: edge-functions-logs
          path: functions_output.txt
          retention-days: 30

      - name: ❌ Edge Functions deployment failed - STOPPING deployment
        if: steps.functions.outputs.functions_status == 'failed'
        run: |
          echo "::error::Edge Functions deployment failed. Deployment aborted."
          echo "Check the edge-functions-logs artifact for details."
          exit 1

  # ============================================================================
  # Phase 4: Vercel Deployment
  # ============================================================================
  deploy:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    needs: [validate, migrate, deploy-functions]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment information
        run: |
          set -euo pipefail
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        shell: bash

      - name: Build project artifacts
        run: |
          set -euo pipefail
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        shell: bash

      - name: Deploy to Vercel Production
        id: deploy
        run: |
          set -euo pipefail
          
          echo "Deploying to Vercel production..."
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 2>&1 | tee deploy_output.txt | tail -1)
          
          if [ -z "$DEPLOYMENT_URL" ]; then
            echo "❌ Deployment failed - no URL returned"
            exit 1
          fi
          
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "✅ Deployment successful: $DEPLOYMENT_URL"
        shell: bash

      - name: Upload deployment logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deployment-logs
          path: deploy_output.txt
          retention-days: 30

      - name: Comment deployment URL on commit
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentUrl = '${{ steps.deploy.outputs.deployment_url }}';
            const commitSha = context.sha;
            
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha,
              body: `🚀 **Production Deployment Successful**\n\n✅ Deployed to: ${deploymentUrl}\n\n**Deployment Details:**\n- Commit: ${commitSha.substring(0, 7)}\n- Workflow: [${context.runNumber}](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
            });

      - name: 🎉 Deployment complete
        run: |
          echo "=========================================="
          echo "🎉 Production deployment completed!"
          echo "=========================================="
          echo "Deployment URL: ${{ steps.deploy.outputs.deployment_url }}"
          echo "Commit: ${{ github.sha }}"
          echo "=========================================="

  # ============================================================================
  # Notification on Failure
  # ============================================================================
  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [validate, migrate, deploy-functions, deploy]
    if: failure()
    
    steps:
      - name: ❌ Deployment failed
        run: |
          echo "::error::Production deployment failed!"
          echo "Check the workflow logs for details:"
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          # You can add additional notification logic here:
          # - Send email via SendGrid/Resend
          # - Post to Slack/Discord
          # - Create GitHub issue
          exit 1
